### ISSUE TITLE
meshio dependency not in setup.py

### ISSUE THREAD

**Issue by celliern** [nschloe/pyfvm#22]
pip install leave an error:
```
Collecting pyfvm
  Downloading pyfvm-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-enpfh0_b/pyfvm/setup.py", line 7, in <module>
        from pyfvm import __version__, __author__, __author_email__
      File "/tmp/pip-build-enpfh0_b/pyfvm/pyfvm/__init__.py", line 4, in <module>
        from . import mesh2d
      File "/tmp/pip-build-enpfh0_b/pyfvm/pyfvm/mesh2d.py", line 5, in <module>
        from pyfvm.base import _base_mesh
      File "/tmp/pip-build-enpfh0_b/pyfvm/pyfvm/base.py", line 34, in <module>
        import meshio
    ModuleNotFoundError: No module named 'meshio'
```
should be fixed by adding it in setup.py

**Comment by nschloe** [comment]
Thanks for the report! I'm currently updating pyfvm for the new voropy, and will fix this along the way.

**Comment by nschloe** [comment]
Fixed now.
